### ISSUE TITLE
Update scroll position when mixing transitionlink and gatsby-link

### ISSUE THREAD

**Issue by TylerBarnes** [TylerBarnes/gatsby-plugin-transition-link#45]
Currently this plugin has disabled Gatsby's `shouldUpdateScroll` browser API because scroll update needs to happen in time with the transition. This causes the scroll position to not update when using gatsby-link together with gatsby-plugin-transition-link. A check should be added to update scroll position when not using transition link.

**Comment by ITSjwags** [comment]
Any ideas on how to resolve this? 

Every link I have stays at the same scroll point from the previous page. I'm never getting to the top of the page on any route/page change. Do you think that is related to this issue?

**Comment by TylerBarnes** [comment]
Hey @ITSjwags yes, for now the solution is to not mix gatsby-link and transition-link. You can use a TL as if it were a normal link with no animation and it should solve the issue. 

I'm looking at spending a good chunk of time fixing and closing issues on this repo this weekend, so likely this will be solved soon. Let me know if you need any more help in the meantime

**Comment by ITSjwags** [comment]
Hmm, I've removed all gatsby link references and switched to use all AniLink and I'm still not getting to the top of the page on any changes from page to page.

**Comment by TylerBarnes** [comment]
That's weird, it should work. If you can provide a demo repo or invite me to a private repo I can debug.

**Comment by ITSjwags** [comment]
I invited you to the private repo I'm developing. If it's too big and hard to debug I'll try to pull some stuff out and make a small demo repo.

**Comment by TylerBarnes** [comment]
@ITSjwags the reason is that your page is scrolling in a child element instead of scrolling the html/body elements.

You can test this by typing `window.scrollTo(0,0)` in the browser console, the page doesn't scroll.
I found in `layout.js` that the issue for some of the pages it that you're scrolling the `<Content />` element by giving it `height: 100vh;` `overflow: hidden;`. If you remove those lines and navigate to the contact page for example you can your page jump to the top. For some of the other pages (for example the work page) it looks like some other css is preventing the window from scrolling. I couldn't find exactly which css was causing that issue though.

If you can't change your css for some reason you can add a custom trigger function to your anilink to scroll the right element. For example:

```jsx
<AniLink
            trigger={async (pages) => {
              const entry = await pages.entry;

              const scrollingEl = entry.node.querySelector('selector-of-element-you-need-to-scroll');

              scrollingEl.scrollTo(0,0);
            }}
            to="/"
            cover
            direction="left"
            bg={theme.colors.secondary}
          >
            <Logo color={theme.colors.secondary} />
          </AniLink>
```

**Comment by TylerBarnes** [comment]
Over in #76 we were discussing a new scrolling API though I haven't 100% thought of what the best way forward is. Maybe it would be good to also add an option for which element to scroll? It would be good to hear any thoughts you may have at #76

**Comment by TylerBarnes** [comment]
By the way your site is looking awesome!

**Comment by ITSjwags** [comment]
Duuuude. Thank you so much! I had some leftover scroll stuff from when I was trying to make scroll-snap work on the site. Didn't even realize it was causing this issue and you found it so fast. haha You're the man!

Also, the site is coming along nicely - thanks to this dope plugin! Much appreciated. I'm still cleaning up some performance smells and optimizing everything along the way. I'll add it to the site list on your README when it's done! :)

**Comment by TylerBarnes** [comment]
Awesome!! Definitely need more sites in the README! Stoked to see it when it's finished.

**Comment by TylerBarnes** [comment]
PS, you can mix gatsby-link and transitionlink/anilink now.
